### ISSUE TITLE
Win生成sdk失败

### ISSUE THREAD

**Issue by iomanip2040** [aliyun/aliyun-openapi-cpp-sdk#107]
Win10 + CMake3.17+VS2017下，生成至第4步
Build and Install C++ SDK
Open aliyun-openapi-cpp-sdk\\sdk_build\\alibabacloud-sdk.sln with Visual Studio
Select Release
Check INSTALL option from Build -> Configuration Manager
Build->Build Solutions to build.

在配置管理中并未生成INSTALL，请问这个是什么问题导致的，谢谢！

整个解决方案有
+ALL_BUID
+ZERO_CHECK
+catch
+curl
+jsoncpp

![解决方案目录](https://user-images.githubusercontent.com/10581394/78916945-ca073180-7ac0-11ea-8c4b-ecdd8ab86434.png)

**Comment by AxiosCros** [comment]
1. 使用 cmake-gui 生成构建 VS 解决方案
* 在 aliyun-openapi-cpp-sdk 下创建 `sdk_build` 目录
* 打开 cmake-gui , 然后进行以下操作
  * 选择 `Browse Source` 为 `源代码目录(aliyun-openapi-cpp-sdk)`
  * 选择 `Browse build` 为 `构建目录(sdk_build)`
  * 点击 `configure`
  * 点击 `generate`, 构建 VS 解决方案。

2. 编译安装 C++ SDK

* 进入 sdk_build 目录，使用 Visual Studio 打开 alibabacloud-sdk.sln 解决方案
* 选择构建 `Release` 输出
* 并打开配置管理器勾选 ***`INSTALL`***
* 构建 -> 生成解决方案

**Alibaba Cloud SDK for C++ 将安装在 `C:\Program File (x86)\alibabacloud-sdk` 目录**

**注意：请以管理员身份运行 Visual Studio 和 cmake-gui，否则无法安装 SDK**

---

注意一下操作步骤是否正确，不能忽略和跳过。
如果在“配置管理器”中没有 INSTALL 选项，说明是在 cmake-gui 生成构建 VS 解决方案时操作错误。

**Comment by iomanip2040** [comment]
并没有忽略和跳过，不过在点击 configure 时会有如下警告：
Project version: 1.36.343
CMake Warning at CMakeLists.txt:61 (message):
  INVALID FOLDER 'BUILD_PRODUCT'=OFF

**Comment by iomanip2040** [comment]
@AxiosCros 
并没有忽略和跳过，不过在点击 configure 时会有如下警告：
Project version: 1.36.343
CMake Warning at CMakeLists.txt:61 (message):
INVALID FOLDER 'BUILD_PRODUCT'=OFF

**Comment by AxiosCros** [comment]
那需要修改下根目录的 CMakeLists.txt 文件了

1. 去掉第 15 行 ```option(BUILD_PRODUCT "Build by lower name of product" OFF)```
2. 去掉 60 至 65 行。
3. 在文件末尾加上想要编译的 SDK , 比如 ```add_subdirectory(ecs)```

**Comment by iomanip2040** [comment]
@AxiosCros 对makelist不熟悉，哈哈，可以正常编译了
不过发现了一个问题。
TwiceTelVerifyResult.h line:53 ,TwiceTelVerifyResult twiceTelVerifyResult_，这里应该是TwiceTelVerifyResult::Result twiceTelVerifyResult_吧？

**Comment by AxiosCros** [comment]
这个是生成错误，要去改下生成器。改好后，会重新发一个版本，并在这里回复。

**Comment by iomanip2040** [comment]
@AxiosCros 感谢帮忙解决问题，新版本发布时麻烦@一下，谢谢。先关闭问题了

**Comment by AxiosCros** [comment]
@iomanip2040 
问题已修复，代码已更新。请获取最新版本。
