### ISSUE TITLE
关于BUILD_PRODUCT

### ISSUE THREAD

**Issue by hb104** [aliyun/aliyun-openapi-cpp-sdk#118]
windows下32位，选择VS2010下congfigure后
产生一个错误Please set the value of 'BUILD_PRODUCT'
，请问如何设置BUILD_PRODUCT呢？

**Comment by AxiosCros** [comment]
在 CMake 图形界面上，BUILD_PRODUCT 参数那里，右侧输入框点一下就进入输入状态了。
比如输入一个 "ecs"，就会编译 ecs sdk
