### ISSUE TITLE
在vs2019(win32)，iot_sdk中RRpcResult::parse解析MessageId错误

### ISSUE THREAD

**Issue by cytj129** [aliyun/aliyun-openapi-cpp-sdk#119]
1、使用std::stol错误，应该替换为std::stoull
2、变量long messageId_改为 unsigned long long messageId_

**Comment by AxiosCros** [comment]
由于接口数据里定义回调数据 messageId 为 Long 类型，所以在生成 SDK 的时候也是根据 long 类型来生成。
目前，我先手动修改，后面尝试完善数据类型的定义及生成。
