### ISSUE TITLE
wincrypt.h  出现大量重复错误信息 error C2146: 语法错误 : 缺少“;”(在标识符“HCRYPTPROV”的前面) error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int

### ISSUE THREAD

**Issue by PongLyon** [aliyun/aliyun-openapi-cpp-sdk#138]
产品和接口：编译alibabacloud-sdk  问题发生时工作所在的产品和调用的API
平台：windows10, VisualStudio Professional 2022, Cmake 3.23.1 

出现此错误是因为在alibabacloud-sdk 的core项目HmacSha1Signer.cc文件，先include <wincrypt.h>。接着才
#include <windows.h>。建议将#include <windows.h>向前移至：

#ifdef _WIN32
#include <windows.h>
#include <wincrypt.h>
#else
#include <openssl/hmac.h>
#endif

修改为以上代码能解决 wincrypt.h  出错问题

**Comment by UnknownObject000** [comment]
> 产品和接口：编译alibabacloud-sdk 问题发生时工作所在的产品和调用的API 平台：windows10, VisualStudio Professional 2022, Cmake 3.23.1
> 
> 出现此错误是因为在alibabacloud-sdk 的core项目HmacSha1Signer.cc文件，先include <wincrypt.h>。接着才 #include <windows.h>。建议将#include <windows.h>向前移至：
> 
> #ifdef _WIN32 #include <windows.h> #include <wincrypt.h> #else #include <openssl/hmac.h> #endif
> 
> 修改为以上代码能解决 wincrypt.h 出错问题

我也遇到了同样的问题，修改后就可以正常通过编译了。
我的环境是：
Windows 11
Visual Studio Professional 2022
CMake 3.23.2

**Comment by SiCoYu** [comment]
void RunCommandRequest::setParameters(std::map<std::string, std::string> parameters) {
  parameters_ = parameters;
  setParameter(std::string("Parameters"), parameters);
}
void InvokeCommandRequest::setParameters(std::map<std::string, std::string> parameters) {
  parameters_ = parameters;
  setParameter(std::string("Parameters"), parameters);
}
参数类型都对不上了，连这种低级错误都能犯，也是够专业的

**Comment by PongLyon** [comment]
> void RunCommandRequest::setParameters(std::map<std::string, std::string> parameters) { parameters_ = parameters; setParameter(std::string("Parameters"), parameters); } void InvokeCommandRequest::setParameters(std::map<std::string, std::string> parameters) { parameters_ = parameters; setParameter(std::string("Parameters"), parameters); } 参数类型都对不上了，连这种低级错误都能犯，也是够专业的

跟官方提了还没人去修改！！！
