### ISSUE TITLE
用 VS 的开发人员命令提示符，执行以下命令编译并安装，error MSB6006

### ISSUE THREAD

**Issue by YiXun1990** [aliyun/aliyun-openapi-cpp-sdk#2]
生成失败。

“D:\Projects\aliyun-openapi-cpp-sdk-master\sdk_build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“D:\Projects\aliyun-openapi-cpp-sdk-master\sdk_build\aegis\aegis.vcxproj”(默认目标) (3) ->
“D:\Projects\aliyun-openapi-cpp-sdk-master\sdk_build\core\core.vcxproj”(默认目标) (4) ->
“D:\Projects\aliyun-openapi-cpp-sdk-master\sdk_build\3rdparty\curl.vcxproj”(默认目标) (5) ->
(CustomBuild 目标) ->
  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(1
71,5): error MSB6006: “cmd.exe”已退出，代码为 1。 [D:\Projects\aliyun-openapi-cpp-sdk-master\sdk_build\3rdparty\curl.vcxproj]

环境：
visual studio 2017
cmake 3.11.1
windows 10 1804

**Comment by zhangzifa** [comment]
This is already been fixe. Please refer to the [README.md](https://github.com/aliyun/aliyun-openapi-cpp-sdk/blob/master/README.md)
