### ISSUE TITLE
官网文档demo中的aos_pool_create段错误

### ISSUE THREAD

**Issue by kite1218** [aliyun/aliyun-openapi-cpp-sdk#3]
环境centos7，demo编译正常，但执行到aos_pool_create时段错误，异常退出，是否对版本有要求？
apr先是按照文档区的sudo yum install curl-devel apr-devel apr-util-devel命令安装，后从阿帕奇官网下载的1.6.3依然崩溃

**Comment by zhangzifa** [comment]
@kite1218  请使用最新版本sdk验证一下是否问题依然存在。谢谢

**Comment by zhangzifa** [comment]
关闭issue，如有问题再reopen
