### ISSUE TITLE
use the tool cmake to create makefile error(ubuntu 16.04 cmake version v3.5 )

### ISSUE THREAD

**Issue by fangkangbest** [aliyun/aliyun-openapi-cpp-sdk#4]
log as below:
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
-- Project version: 1.20.0
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1850 (message):
  URL_HASH is set to

    MD5=9b3d2cb5c0f9532cddfbbfd0a622f0af;DOWNLOAD_NO_EXTRACT;1

  but must be ALGO=value where ALGO is

    MD5|SHA1|SHA224|SHA256|SHA384|SHA512

  and value is a hex string.
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  3rdparty/CMakeLists.txt:44 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/frank/aliyun/aliyun-openapi-cpp-sdk/CMakeFiles/CMakeOutput.log".
frank@ubuntu:~/aliyun/aliyun-openapi-cpp-sdk$ 
frank@ubuntu:~/aliyun/aliyun-openapi-cpp-sdk$ cmake CMakeLists.txt 
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
-- Project version: 1.20.0
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1850 (message):
  URL_HASH is set to

    MD5=9b3d2cb5c0f9532cddfbbfd0a622f0af;DOWNLOAD_NO_EXTRACT;1

  but must be ALGO=value where ALGO is

    MD5|SHA1|SHA224|SHA256|SHA384|SHA512

  and value is a hex string.
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  3rdparty/CMakeLists.txt:44 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/frank/aliyun/aliyun-openapi-cpp-sdk/CMakeFiles/CMakeOutput.log".

**Comment by JacksonTian** [comment]
看报错信息是 libcurl 不存在？

**Comment by fangkangbest** [comment]
libcurl 这个我安装过了。
frank@ubuntu:~$ curl --version
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.0.2g zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

**Comment by helenchw** [comment]
I also encountered the same CMake error on Ubuntu 16.04 with CMake 3.5.

A workaround is to modify the lines for the external project "catch" in `3rdparty/CMakeLists.txt` as follows:
```
ExternalProject_Add(catch
    URL ${CMAKE_CURRENT_SOURCE_DIR}/catch-2.0.1.hpp
    URL_HASH MD5=9b3d2cb5c0f9532cddfbbfd0a622f0af
    DOWNLOAD_COMMAND ""
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_SOURCE_DIR}/catch-2.0.1.hpp <INSTALL_DIR>/catch.hpp
)
```

**Comment by fangkangbest** [comment]
it's ok. Thanks a lot.

> I also encountered the same CMake error on Ubuntu 16.04 with CMake 3.5.
> A workaround is to modify the lines for the external project "catch" in 3rdparty/CMakeLists.txt as follows:
> ExternalProject_Add(catch
>     URL ${CMAKE_CURRENT_SOURCE_DIR}/catch-2.0.1.hpp
>     URL_HASH MD5=9b3d2cb5c0f9532cddfbbfd0a622f0af
>     DOWNLOAD_COMMAND ""
>     CONFIGURE_COMMAND ""
>     BUILD_COMMAND ""
>     INSTALL_COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_SOURCE_DIR}/catch-2.0.1.hpp <INSTALL_DIR>/catch.hpp
> )

it's ok. thanks a lot.

**Comment by zhangzifa** [comment]
This is already been fixed [fix build failed](https://github.com/aliyun/aliyun-openapi-cpp-sdk/pull/11). 
I close this issue.
