### ISSUE TITLE
搭建基于 appveyor 的测试

### ISSUE THREAD

**Issue by JacksonTian** [aliyun/aliyun-openapi-cpp-sdk#42]
* **产品和接口**:
* **平台**:
* **最小代码**:

**Comment by zhangzifa** [comment]
下周做，

**Comment by perfectsun1990** [comment]
哈喽~ 阿里的小伙伴， 问一下我按照Readme按照时遇到点问题。
求解。
提示：无法找到Double和Json的类型，但依赖我都装好了，jsoncpp我自己测试的程序可以通过。
Json和Double应该是你们引用或再封装的自定义的对象类型吧？
系统：centos7.5、gcc5.3
步骤：直接执行easyinstall.sh

![image](https://user-images.githubusercontent.com/22425871/58607700-31fec000-82d3-11e9-9538-b920849cd867.png)

**Comment by JacksonTian** [comment]
我帮你看看

**Comment by JacksonTian** [comment]
@perfectsun1990 暂时性的只能请你先用 1.36.11 tag 之前的版本了。

**Comment by perfectsun1990** [comment]
好的~

**Comment by perfectsun1990** [comment]
编译了1.36.10的版本，能跑readme的例子，但不能跑起来https://help.aliyun.com/document_detail/108563.html?spm=a2c4g.11186623.6.551.53645b0eWAbqIK
上面的例子，我购买了实时翻译的业务，望您能帮忙提供个解决方案，或者您那边直接发我一个在Centos6/7可用demo吧，谢谢！

**Comment by perfectsun1990** [comment]
@JacksonTian 编译了1.36.10的版本，能跑readme的例子，但不能跑起来https://help.aliyun.com/document_detail/108563.html?spm=a2c4g.11186623.6.551.53645b0eWAbqIK
上面的例子，我购买了实时翻译的业务，望您能帮忙提供个解决方案，或者您那边直接发我一个在Centos6/7可用demo吧，谢谢！

**Comment by perfectsun1990** [comment]
@JacksonTian 编译了1.36.10的版本，能跑readme的例子，但不能跑起来https://help.aliyun.com/document_detail/108563.html?spm=a2c4g.11186623.6.551.53645b0eWAbqIK
上面的例子，我购买了实时翻译的业务，望您能帮忙提供个解决方案，或者您那边直接发我一个在Centos6/7可用demo吧，谢谢！
![image](https://user-images.githubusercontent.com/22425871/58620625-207cde80-82fa-11e9-9d95-79bff3c196cc.png)

**Comment by zhangzifa** [comment]
@perfectsun1990  `AlimtClient` 替换 `EcsClient` 试试看。  
 ```c
EcsClient client("<your-access-key-id>", "<your-access-key-secret>", configuration);
```

**Comment by yanminhui** [comment]
> @perfectsun1990 暂时性的只能请你先用 1.36.11 tag 之前的版本了。

试了好几个版本同样在 `Visual Studio 2015` 上编译错误，控制好 release，确保编译正常。或者在 dev 分支上开发，测试完整后再合并到 master 上。

**Comment by blademaster98** [comment]
我还刚开了个issue ，这么大的公司，这么主流的语言，居然不好好的支持，真让人失望！作为一名C++ newbee,  wanna throw so much shit on all your face. Shame on all of you.

**Comment by songshenzong** [comment]
> 我还刚开了个issue ，这么大的公司，这么主流的语言，居然不好好的支持，真让人失望！作为一名C++ newbee, wanna throw so much shit on all your face. Shame on all of you.

请问您的电子邮箱是什么? 或者提供一个联系方式。

**Comment by blademaster98** [comment]
never mind, I wrote a small sdk to cover my own demand, easy task.

**Comment by Jack091545** [comment]
编译两次，怀疑人生。


commit f90c2115c9683257e04b6c81fb282f2085d8cba9 (HEAD -> 1.36.295, tag: 1.36.295, origin/master, origin/HEAD, master)

```
[ 64%] Building CXX object `alimt/CMakeFiles/alimt.dir/src/model/CreateDocTranslateTaskRequest.cc.o`
/home/weiming/aliyun-openapi-cpp-sdk-master/alimt/src/model/CreateDocTranslateTaskRequest.cc: In constructor ‘AlibabaCloud::Alimt::Model::CreateDocTranslateTaskRequest::CreateDocTranslateTaskRequest()’:
/home/weiming/aliyun-openapi-cpp-sdk-master/alimt/src/model/CreateDocTranslateTaskRequest.cc:24:33: error: ‘POST’ is not a member of ‘AlibabaCloud::HttpRequest::Method’
  setMethod(HttpRequest::Method::POST);
                                 ^~~~
alimt/CMakeFiles/alimt.dir/build.make:86: recipe for target 'alimt/CMakeFiles/alimt.dir/src/model/CreateDocTranslateTaskRequest.cc.o' failed
make[2]: *** [alimt/CMakeFiles/alimt.dir/src/model/CreateDocTranslateTaskRequest.cc.o] Error 1
CMakeFiles/Makefile2:2340: recipe for target 'alimt/CMakeFiles/alimt.dir/all' failed
make[1]: *** [alimt/CMakeFiles/alimt.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```
