### ISSUE TITLE
CmakeLists.txt中部分文件被替换成错误的路径

### ISSUE THREAD

**Issue by SevenChen1996** [aliyun/aliyun-openapi-cpp-sdk#66]
如下位置
cloudapi/CMakeLists.txt:234:    src/com.aliyun.pop.sdk.domain.Product@383790cfClient.cc
ecs/CMakeLists.txt:570: src/com.aliyun.pop.sdk.domain.Product@5c313224Client.cc
market/CMakeLists.txt:70:       src/com.aliyun.pop.sdk.domain.Product@6f1c29b7Client.cc
polardb/CMakeLists.txt:128:     src/com.aliyun.pop.sdk.domain.Product@3ff57625Client.cc
bssopenapi/CMakeLists.txt:122:  src/com.aliyun.pop.sdk.domain.Product@2fc0cc3Client.cc
ccc/CMakeLists.txt:346: src/com.aliyun.pop.sdk.domain.Product@7b78ed6aClient.cc
dypnsapi/CMakeLists.txt:34:     src/com.aliyun.pop.sdk.domain.Product@28f2a10fClient.cc
cusanalytic_sc_online/CMakeLists.txt:54:        src/com.aliyun.pop.sdk.domain.Product@6c284afClient.cc
slb/CMakeLists.txt:184: src/com.aliyun.pop.sdk.domain.Product@5fc930f0Client.cc
rds/CMakeLists.txt:362: src/com.aliyun.pop.sdk.domain.Product@79ab97fdClient.cc
vpc/CMakeLists.txt:462: src/com.aliyun.pop.sdk.domain.Product@3292d91aClient.cc
foas/CMakeLists.txt:150:        src/com.aliyun.pop.sdk.domain.Product@57eda880Client.cc
elasticsearch/CMakeLists.txt:126:       src/com.aliyun.pop.sdk.domain.Product@180da663Client.cc

**Comment by AxiosCros** [comment]
@SevenChen1996 

感谢反馈，问题正在解决中。
