### ISSUE TITLE
编译过程中出现问题

### ISSUE THREAD

**Issue by SevenChen1996** [aliyun/aliyun-openapi-cpp-sdk#67]
![image](https://user-images.githubusercontent.com/27799095/64906197-e6531380-d715-11e9-94bf-4573eaf23e99.png)
出现如上问题，不知是否为编译流程不正确

**Comment by AxiosCros** [comment]
生成老版本 SDK 时误添加了不存在的 Request 文件，问题已解决，已重新发布 ARMS 的新版 SDK 。
@SevenChen1996

**Comment by SevenChen1996** [comment]
感谢。但是编译还是不成功，涉及到：
1. 数据类型未定义
![image](https://user-images.githubusercontent.com/27799095/64910037-7492be00-d745-11e9-82ae-3f004aa8ed71.png)
2.extern是个关键字吧
![image](https://user-images.githubusercontent.com/27799095/64910290-3f876b00-d747-11e9-9e14-385f0cf7d343.png)

**Comment by AxiosCros** [comment]
@SevenChen1996 

感谢反馈。问题已经在处理中。

**Comment by AxiosCros** [comment]
@SevenChen1996 

通过修改 SDK 生成器，已处理了多层 RepeatList 接口参数类型的嵌套。
EHPC cpp sdk 已发布新版本。

**Comment by SevenChen1996** [comment]
貌似还是有问题。涉及到一些数据类型的问题。。。。。。

**Comment by AxiosCros** [comment]
@SevenChen1996 

我这里只发现了 aegis 有 extern 关键字名称作参数的问题，已发布这个产品的 cpp sdk 了。
其它问题，可以详细说明下吗？

**Comment by SevenChen1996** [comment]
编译的错误输出如下所示：
In file included from /home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/EHPCClient.h:139:0,
                 from /home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/src/EHPCClient.cc:17:
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h:55:17: error: ‘Roles’ was not declared in this scope
     std::vector<Roles> getRoles()const;
                 ^~~~~
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h:55:22: error: template argument 1 is invalid
     std::vector<Roles> getRoles()const;
                      ^
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h:55:22: error: template argument 2 is invalid
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h:56:37: error: ‘Roles’ was not declared in this scope
     void setRoles(const std::vector<Roles>& roles);
                                     ^~~~~
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h:56:37: note: suggested alternative: ‘getRoles’
     void setRoles(const std::vector<Roles>& roles);
                                     ^~~~~
                                     getRoles
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h:56:42: error: template argument 1 is invalid
     void setRoles(const std::vector<Roles>& roles);
                                          ^
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h:56:42: error: template argument 2 is invalid
In file included from /home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/EHPCClient.h:145:0,
                 from /home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/src/EHPCClient.cc:17:
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigRequest.h:81:17: error: ‘InstanceTypes’ was not declared in this scope
     std::vector<InstanceTypes> getInstanceTypes()const;
                 ^~~~~~~~~~~~~
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigRequest.h:81:30: error: template argument 1 is invalid
     std::vector<InstanceTypes> getInstanceTypes()const;
                              ^
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigRequest.h:81:30: error: template argument 2 is invalid
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigRequest.h:82:45: error: ‘InstanceTypes’ was not declared in this scope
     void setInstanceTypes(const std::vector<InstanceTypes>& instanceTypes);
                                             ^~~~~~~~~~~~~
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigRequest.h:82:45: note: suggested alternative: ‘getInstanceTypes’
     void setInstanceTypes(const std::vector<InstanceTypes>& instanceTypes);
                                             ^~~~~~~~~~~~~
                                             getInstanceTypes
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigRequest.h:82:58: error: template argument 1 is invalid
     void setInstanceTypes(const std::vector<InstanceTypes>& instanceTypes);
                                                          ^
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigRequest.h:82:58: error: template argument 2 is invalid
In file included from /home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/EHPCClient.h:187:0,
                 from /home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/src/EHPCClient.cc:17:
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h:64:17: error: ‘Roles’ was not declared in this scope
     std::vector<Roles> getRoles()const;
                 ^~~~~
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h:64:22: error: template argument 1 is invalid
     std::vector<Roles> getRoles()const;
                      ^
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h:64:22: error: template argument 2 is invalid
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h:65:37: error: ‘Roles’ was not declared in this scope
     void setRoles(const std::vector<Roles>& roles);
                                     ^~~~~
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h:65:37: note: suggested alternative: ‘getRoles’
     void setRoles(const std::vector<Roles>& roles);
                                     ^~~~~
                                     getRoles
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h:65:42: error: template argument 1 is invalid
     void setRoles(const std::vector<Roles>& roles);
                                          ^
/home/seven/mylib/aliyun-openapi-cpp-sdk/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h:65:42: error: temp

**Comment by AxiosCros** [comment]
@SevenChen1996 

问题已修复，相关文件已更新。

[UpdateClusterVolumesRequest.h](https://github.com/aliyun/aliyun-openapi-cpp-sdk/blob/master/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h)

[SetAutoScaleConfigResult.h](https://github.com/aliyun/aliyun-openapi-cpp-sdk/blob/master/ehpc/include/alibabacloud/ehpc/model/SetAutoScaleConfigResult.h)

[CreateClusterRequest.h](https://github.com/aliyun/aliyun-openapi-cpp-sdk/blob/master/ehpc/include/alibabacloud/ehpc/model/CreateClusterRequest.h)

**Comment by SevenChen1996** [comment]
如下错误：
UpdateClusterVolumesRequest.cc:44:55: error: ‘struct AlibabaCloud::EHPC::Model::UpdateClusterVolumesRequest::AdditionalVolumes’ has no member named ‘roles’; did you mean ‘Roles’?

修改为：
setCoreParameter(str + ".Roles", std::to_string(obj.Roles.name)); ?

**Comment by SevenChen1996** [comment]
如下错误：
UpdateClusterVolumesRequest.cc:44:55: error: ‘struct AlibabaCloud::EHPC::Model::UpdateClusterVolumesRequest::AdditionalVolumes’ has no member named ‘roles’; did you mean ‘Roles’?

在ehpc/src/model/UpdateClusterVolumesRequest.cc:39 定义了
struct Roles
{
	std::string name;
};
但并未定义roles 成员变量。

**Comment by AxiosCros** [comment]
@SevenChen1996 

已发布新版 ehpc cpp sdk。

[UpdateClusterVolumesRequest.h](https://github.com/aliyun/aliyun-openapi-cpp-sdk/blob/master/ehpc/include/alibabacloud/ehpc/model/UpdateClusterVolumesRequest.h) 已定义 roles 属性

**Comment by SevenChen1996** [comment]
我想这个问题还是存在。
感觉团队可以先进行编译检查然后进行发布。
麻烦修改了。

**Comment by AxiosCros** [comment]
感谢建议，后续我们会考虑增加这个功能的。问题暂时已解决的话，那我先关闭这个 issue 了。
如还有其它问题，您可以继续提交 issue 。
