### ISSUE TITLE
curl.vcproj生成失败

### ISSUE THREAD

**Issue by UnknownObject000** [aliyun/aliyun-openapi-cpp-sdk#81]
编译SDK时发生错误，无法完成编译。提示为生成curl.vcproj失败。
生成平台：Windows10 1903
CMake版本：3.16.0
编译器：MSVC2017（Visual Studio 2017）

编译输出：
1>------ 已启动全部重新生成: 项目: ZERO_CHECK, 配置: Release Win32 ------
1>Checking Build System
2>------ 已启动全部重新生成: 项目: jsoncpp (ExternalProjectTargets\jsoncpp\jsoncpp), 配置: Release Win32 ------
3>------ 已启动全部重新生成: 项目: curl (ExternalProjectTargets\curl\curl), 配置: Release Win32 ------
4>------ 已启动全部重新生成: 项目: catch (ExternalProjectTargets\catch\catch), 配置: Release Win32 ------
2>Creating directories for 'jsoncpp'
2>Building Custom Rule F:/aliyun-openapi-cpp-sdk-master/3rdparty/CMakeLists.txt
3>Creating directories for 'curl'
2>Performing download step (verify and extract) for 'jsoncpp'
2>-- verifying file...
2>     file='F:/aliyun-openapi-cpp-sdk-master/3rdparty/jsoncpp-0.10.5.tar.gz'
2>-- verifying file... done
2>-- extracting...
2>     src='F:/aliyun-openapi-cpp-sdk-master/3rdparty/jsoncpp-0.10.5.tar.gz'
2>     dst='F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/src/jsoncpp'
2>-- extracting... [tar xfz]
3>Building Custom Rule F:/aliyun-openapi-cpp-sdk-master/3rdparty/CMakeLists.txt
3>Performing download step (verify and extract) for 'curl'
3>-- verifying file...
3>     file='F:/aliyun-openapi-cpp-sdk-master/3rdparty/curl-7.55.1.tar.gz'
3>-- verifying file... done
3>-- extracting...
3>     src='F:/aliyun-openapi-cpp-sdk-master/3rdparty/curl-7.55.1.tar.gz'
3>     dst='F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/curl-prefix/src/curl'
3>-- extracting... [tar xfz]
4>Creating directories for 'catch'
2>-- extracting... [analysis]
2>-- extracting... [rename]
4>Building Custom Rule F:/aliyun-openapi-cpp-sdk-master/3rdparty/CMakeLists.txt
4>No download step for 'catch'
2>-- extracting... [clean up]
2>-- extracting... done
4>No update step for 'catch'
4>No patch step for 'catch'
2>No update step for 'jsoncpp'
4>No configure step for 'catch'
4>No build step for 'catch'
2>No patch step for 'jsoncpp'
2>Performing configure step for 'jsoncpp'
4>Performing install step for 'catch'
4>Completed 'catch'
2>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
2>-- JsonCpp Version: 0.10.5
2>CMake Warning (dev) at CMakeLists.txt:101 (elseif):
2>  Policy CMP0054 is not set: Only interpret if() arguments as variables or
2>  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
2>  details.  Use the cmake_policy command to set the policy and suppress this
2>  warning.
2>
2>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
2>  is set to NEW.  Since the policy is not set the OLD behavior will be used.
2>This warning is for project developers.  Use -Wno-dev to suppress it.
2>
2>-- Configuring done
2>-- Generating done
2>-- Build files have been written to: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/src/jsoncpp-build
2>Performing build step for 'jsoncpp'
2>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
2>版权所有(C) Microsoft Corporation。保留所有权利。
2>
2>  jsoncpp_lib_static.vcxproj -> F:\aliyun-openapi-cpp-sdk-master\sdk_build\3rdparty\jsoncpp-prefix\src\jsoncpp-build\src\lib_json\Release\jsoncpp.lib
3>-- extracting... [analysis]
2>Performing install step for 'jsoncpp'
2>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
2>版权所有(C) Microsoft Corporation。保留所有权利。
2>
3>-- extracting... [rename]
2>  jsoncpp_lib_static.vcxproj -> F:\aliyun-openapi-cpp-sdk-master\sdk_build\3rdparty\jsoncpp-prefix\src\jsoncpp-build\src\lib_json\Release\jsoncpp.lib
2>  -- Install configuration: "Release"
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/lib/jsoncpp.lib
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/assertions.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/autolink.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/config.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/features.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/forwards.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/json.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/reader.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/value.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/version.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/jsoncpp-prefix/include/json/writer.h
2>Completed 'jsoncpp'
3>-- extracting... [clean up]
3>-- extracting... done
3>No update step for 'curl'
3>No patch step for 'curl'
3>Performing configure step for 'curl'
3>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
3>CMake Warning at CMakeLists.txt:49 (message):
3>  the curl cmake build system is poorly maintained.  Be aware
3>
3>
3>-- curl version=[7.55.1]
3>CMake Error at D:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
3>  Could NOT find Perl (missing: PERL_EXECUTABLE)
3>Call Stack (most recent call first):
3>  D:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
3>  D:/Program Files/CMake/share/cmake-3.16/Modules/FindPerl.cmake:76 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
3>  CMakeLists.txt:224 (find_package)
3>
3>
3>-- Configuring incomplete, errors occurred!
3>See also "F:/aliyun-openapi-cpp-sdk-master/sdk_build/3rdparty/curl-prefix/src/curl-build/CMakeFiles/CMakeOutput.log".
3>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: “cmd.exe”已退出，代码为 1。
3>已完成生成项目“curl.vcxproj”的操作 - 失败。

VS提示找不到<curl/curl.h>，下载最新版本curl库文件并配置引用（include）目录无法解决问题。

**Comment by AxiosCros** [comment]
请安装 perl，或者使用 [git-bash](https://git-scm.com/) 里的 perl.exe，将其所在路径添加至环境变量。
