### ISSUE TITLE
green模块编译错误

### ISSUE THREAD

**Issue by bilinxing** [aliyun/aliyun-openapi-cpp-sdk#82]
* **Product and API**:green
* **Platform**:ubuntu 18
* **How to Reproduce**

    *  编译错误：
In file included from /home/ya/ali_sdk/aliyun-openapi-cpp-sdk/green/src/model/DescribeCustomOcrTemplateResult.cc:17:0:  /home/ya/ali_sdk/aliyun-openapi-cpp-sdk/green/include/alibabacloud/green/model/DescribeCustomOcrTemplateResult.h:45:13: error: redefinition of ‘struct AlibabaCloud::Green::Model::DescribeCustomOcrTemplateResult::OcrTemplate::Item’
      struct Item
             ^~~~
/home/ya/ali_sdk/aliyun-openapi-cpp-sdk/green/include/alibabacloud/green/model/DescribeCustomOcrTemplateResult.h:37:13: 

    *  源码
      /aliyun-openapi-cpp-sdk/green/include/alibabacloud/green/model/DescribeCustomOcrTemplateResult.h:45

    	struct OcrTemplate
				{
					struct Item
					{
						int x;
						int y;
						int height;
						int width;
						std::string name;
					};
					struct Item
					{
						int x;
						int y;
						int height;
						int width;
						std::string name;
					};
					std::vector<OcrTemplate::Item> referArea;
					int status;
					std::vector<OcrTemplate::Item> recognizeArea;
					long id;
					std::string imgUrl;
					std::string name;
				};

**Comment by AxiosCros** [comment]
green 这个产品的接口同时存在 Roa 和 Rpc 风格，目前 C++ SDK Core 暂不支持这样的多版本接口共存。我可以提交一版只有一种风格接口的 PR，但是会删除不少接口。
