### ISSUE TITLE
中英文Readme不一致/Chinese and English readme are inconsistent

### ISSUE THREAD

**Issue by UnknownObject000** [aliyun/aliyun-openapi-cpp-sdk#83]
中英文两个版本的Readme文件不一致，在英语版本的文件中，Windows平台编译要求安装Perl，而中文版本的没有这项要求。请问Perl是否是Windows平台编译SDK必须的条件？以及是否需要在Windows平台上安装curl等第三方库？
The Chinese and English versions of readme files are inconsistent. In the English version, Perl is required for Windows platform compilation, but not for the Chinese version. Is Perl a necessary condition for compiling SDK on Windows platform? And do you need to install curl and other third-party libraries on Windows platform?

**Comment by AxiosCros** [comment]
感谢反馈，中英文 README 已完善。
相关 PR #84
