### ISSUE TITLE
build failed: JSONCPP_STRING: undeclared identifier 

### ISSUE THREAD

**Issue by philohack** [aliyun/aliyun-openapi-cpp-sdk#87]
The aliyun-openapi-cpp-sdk-1.36.220.zip built failed according to README.md in the source folder.
It says,
**Error	C2065	'JSONCPP_STRING': undeclared identifier** **CreateClusterByResourcesGroupResult.cc	42**

**Comment by philohack** [comment]
On Windows 10 using VS2017.

**Comment by AxiosCros** [comment]
jsoncpp dependency package is not installed successfully.
