### ISSUE TITLE
无法编译64位版本

### ISSUE THREAD

**Issue by UnknownObject000** [aliyun/aliyun-openapi-cpp-sdk#90]
**编译平台：**
Windows10 1909
Visual Studio 2017
CMake 3.16.0

在CMake生成的解决方案中，配置管理器中仅有“WIN32”选项而没有“x64”选项。在配置管理器中选择“新建”、“x64”、从“WIN32”复制配置，使用此配置构建SDK，出现“fatal error LNK1112： 模块计算机类型“x64”与目标计算机类型“x86”冲突”错误。请问如何正确编译64位的SDK。

**Comment by UnknownObject000** [comment]
因为我只需要core与alidns模块，因此我对CMakeLists.txt文件做出了修改。附上我修改之后的文件。
[CMakeLists.txt](https://github.com/aliyun/aliyun-openapi-cpp-sdk/files/4023310/CMakeLists.txt)

**Comment by UnknownObject000** [comment]
另附VS的编译输出。
1>------ 已启动全部重新生成: 项目: ZERO_CHECK, 配置: Release x64 ------
1>Checking Build System
2>------ 已启动全部重新生成: 项目: curl (ExternalProjectTargets\curl\curl), 配置: Release x64 ------
3>------ 已启动全部重新生成: 项目: jsoncpp (ExternalProjectTargets\jsoncpp\jsoncpp), 配置: Release x64 ------
4>------ 已启动全部重新生成: 项目: catch (ExternalProjectTargets\catch\catch), 配置: Release x64 ------
2>Creating directories for 'curl'
3>Creating directories for 'jsoncpp'
4>Creating directories for 'catch'
2>Building Custom Rule F:/aliyun-openapi-cpp-sdk/3rdparty/CMakeLists.txt
2>Performing download step (verify and extract) for 'curl'
3>Building Custom Rule F:/aliyun-openapi-cpp-sdk/3rdparty/CMakeLists.txt
4>Building Custom Rule F:/aliyun-openapi-cpp-sdk/3rdparty/CMakeLists.txt
2>-- verifying file...
2>     file='F:/aliyun-openapi-cpp-sdk/3rdparty/curl-7.55.1.tar.gz'
3>Performing download step (verify and extract) for 'jsoncpp'
4>No download step for 'catch'
4>No update step for 'catch'
3>-- verifying file...
3>     file='F:/aliyun-openapi-cpp-sdk/3rdparty/jsoncpp-0.10.5.tar.gz'
3>-- verifying file... done
2>-- verifying file... done
3>-- extracting...
3>     src='F:/aliyun-openapi-cpp-sdk/3rdparty/jsoncpp-0.10.5.tar.gz'
3>     dst='F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/src/jsoncpp'
3>-- extracting... [tar xfz]
4>No patch step for 'catch'
4>No configure step for 'catch'
2>-- extracting...
2>     src='F:/aliyun-openapi-cpp-sdk/3rdparty/curl-7.55.1.tar.gz'
2>     dst='F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/src/curl'
2>-- extracting... [tar xfz]
4>No build step for 'catch'
4>Performing install step for 'catch'
4>Completed 'catch'
3>-- extracting... [analysis]
3>-- extracting... [rename]
3>-- extracting... [clean up]
3>-- extracting... done
3>No update step for 'jsoncpp'
3>No patch step for 'jsoncpp'
3>Performing configure step for 'jsoncpp'
3>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
3>-- JsonCpp Version: 0.10.5
3>CMake Warning (dev) at CMakeLists.txt:101 (elseif):
3>  Policy CMP0054 is not set: Only interpret if() arguments as variables or
3>  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
3>  details.  Use the cmake_policy command to set the policy and suppress this
3>  warning.
3>
3>  Quoted variables like "MSVC" will no longer be dereferenced when the policy
3>  is set to NEW.  Since the policy is not set the OLD behavior will be used.
3>This warning is for project developers.  Use -Wno-dev to suppress it.
3>
3>-- Configuring done
3>-- Generating done
3>-- Build files have been written to: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/src/jsoncpp-build
3>Performing build step for 'jsoncpp'
3>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
3>版权所有(C) Microsoft Corporation。保留所有权利。
3>
2>-- extracting... [analysis]
2>-- extracting... [rename]
3>  jsoncpp_lib_static.vcxproj -> F:\aliyun-openapi-cpp-sdk\sdk_build\3rdparty\jsoncpp-prefix\src\jsoncpp-build\src\lib_json\Release\jsoncpp.lib
3>Performing install step for 'jsoncpp'
3>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
3>版权所有(C) Microsoft Corporation。保留所有权利。
3>
3>  jsoncpp_lib_static.vcxproj -> F:\aliyun-openapi-cpp-sdk\sdk_build\3rdparty\jsoncpp-prefix\src\jsoncpp-build\src\lib_json\Release\jsoncpp.lib
3>  -- Install configuration: "Release"
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/lib/jsoncpp.lib
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/assertions.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/autolink.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/config.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/features.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/forwards.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/json.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/reader.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/value.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/version.h
3>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/jsoncpp-prefix/include/json/writer.h
3>Completed 'jsoncpp'
2>-- extracting... [clean up]
2>-- extracting... done
2>No update step for 'curl'
2>No patch step for 'curl'
2>Performing configure step for 'curl'
2>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
2>CMake Warning at CMakeLists.txt:49 (message):
2>  the curl cmake build system is poorly maintained.  Be aware
2>
2>
2>-- curl version=[7.55.1]
2>-- Could NOT find LibSSH2 (missing: LIBSSH2_INCLUDE_DIR LIBSSH2_LIBRARY)
2>-- Enabled features: WinSSL IPv6 AsynchDNS Largefile SSPI SPNEGO Kerberos NTLM
2>-- Enabled protocols: HTTP HTTPS
2>-- Configuring done
2>-- Generating done
2>-- Build files have been written to: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/src/curl-build
2>Performing build step for 'curl'
2>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
2>版权所有(C) Microsoft Corporation。保留所有权利。
2>
2>  libcurl.vcxproj -> F:\aliyun-openapi-cpp-sdk\sdk_build\3rdparty\curl-prefix\src\curl-build\lib\Release\libcurl.lib
2>Performing install step for 'curl'
2>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
2>版权所有(C) Microsoft Corporation。保留所有权利。
2>
2>  libcurl.vcxproj -> F:\aliyun-openapi-cpp-sdk\sdk_build\3rdparty\curl-prefix\src\curl-build\lib\Release\libcurl.lib
2>  -- Install configuration: "Release"
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/bin/curl-config
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/lib/pkgconfig/libcurl.pc
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/curl.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/curlver.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/easy.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/mprintf.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/multi.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/stdcheaders.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/system.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/include/curl/typecheck-gcc.h
2>  -- Up-to-date: F:/aliyun-openapi-cpp-sdk/sdk_build/3rdparty/curl-prefix/lib/libcurl.lib
2>Completed 'curl'
5>------ 已启动全部重新生成: 项目: core, 配置: Release x64 ------
5>Building Custom Rule F:/aliyun-openapi-cpp-sdk/core/CMakeLists.txt
5>AlibabaCloud.cc
5>AsyncCallerContext.cc
5>ClientConfiguration.cc
5>CommonClient.cc
5>CommonRequest.cc
5>CommonResponse.cc
5>CoreClient.cc
5>Credentials.cc
5>CredentialsProvider.cc
5>CurlHttpClient.cc
5>EcsMetadataFetcher.cc
5>EndpointProvider.cc
5>Error.cc
5>Executor.cc
5>HmacSha1Signer.cc
5>F:\aliyun-openapi-cpp-sdk\core\src\HmacSha1Signer.cc(43): warning C4200: 使用了非标准扩展: 结构/联合中的零大小数组
5>F:\aliyun-openapi-cpp-sdk\core\src\HmacSha1Signer.cc(43): note: 默认构造函数或 copy/move 赋值运算符将忽略此成员
5>F:\aliyun-openapi-cpp-sdk\core\src\HmacSha1Signer.cc(46): warning C4267: “初始化”: 从“size_t”转换到“DWORD”，可能丢失数据
5>F:\aliyun-openapi-cpp-sdk\core\src\HmacSha1Signer.cc(52): warning C4267: “=”: 从“size_t”转换到“DWORD”，可能丢失数据
5>F:\aliyun-openapi-cpp-sdk\core\src\HmacSha1Signer.cc(69): warning C4267: “参数”: 从“size_t”转换到“DWORD”，可能丢失数据
5>HttpClient.cc
5>HttpMessage.cc
5>HttpResponse.cc
5>HttpRequest.cc
5>InstanceProfileCredentialsProvider.cc
5>F:\aliyun-openapi-cpp-sdk\core\include\alibabacloud/core/InstanceProfileCredentialsProvider.h(30): warning C4275: 非 dll 接口 class“AlibabaCloud::EcsMetadataFetcher”用作 dll 接口 class“AlibabaCloud::InstanceProfileCredentialsProvider”的基
5>f:\aliyun-openapi-cpp-sdk\core\src\EcsMetadataFetcher.h(30): note: 参见“AlibabaCloud::EcsMetadataFetcher”的声明
5>F:\aliyun-openapi-cpp-sdk\core\include\alibabacloud/core/InstanceProfileCredentialsProvider.h(29): note: 参见“AlibabaCloud::InstanceProfileCredentialsProvider”的声明
5>正在生成代码...
5>正在编译...
5>NetworkProxy.cc
5>Outcome.cc
5>Runnable.cc
5>RoaServiceClient.cc
5>RoaServiceRequest.cc
5>RpcServiceClient.cc
5>RpcServiceRequest.cc
5>ServiceRequest.cc
5>ServiceResult.cc
5>Signer.cc
5>SimpleCredentialsProvider.cc
5>StsAssumeRoleCredentialsProvider.cc
5>Url.cc
5>Utils.cc
5>F:\aliyun-openapi-cpp-sdk\core\src\Utils.cc(54): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
5>F:\aliyun-openapi-cpp-sdk\core\src\Utils.cc(65): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
5>F:\aliyun-openapi-cpp-sdk\core\src\Utils.cc(82): warning C4267: “参数”: 从“size_t”转换到“DWORD”，可能丢失数据
5>LocationClient.cc
5>LocationRequest.cc
5>DescribeEndpointsRequest.cc
5>DescribeEndpointsResult.cc
5>StsClient.cc
5>StsRequest.cc
5>正在生成代码...
5>正在编译...
5>AssumeRoleRequest.cc
5>AssumeRoleResult.cc
5>GetCallerIdentityRequest.cc
5>GetCallerIdentityResult.cc
5>正在生成代码...
5>x64\Release\AlibabaCloud.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突
5>已完成生成项目“core.vcxproj”的操作 - 失败。
6>------ 已启动全部重新生成: 项目: alidns, 配置: Release x64 ------
6>Building Custom Rule F:/aliyun-openapi-cpp-sdk/alidns/CMakeLists.txt
6>AlidnsClient.cc
6>AddCustomLineRequest.cc
6>AddCustomLineResult.cc
6>AddDomainRequest.cc
6>AddDomainResult.cc
6>AddDomainBackupRequest.cc
6>AddDomainBackupResult.cc
6>AddDomainGroupRequest.cc
6>AddDomainGroupResult.cc
6>AddDomainRecordRequest.cc
6>AddDomainRecordResult.cc
6>AddGtmAccessStrategyRequest.cc
6>AddGtmAccessStrategyResult.cc
6>AddGtmAddressPoolRequest.cc
6>AddGtmAddressPoolResult.cc
6>AddGtmMonitorRequest.cc
6>AddGtmMonitorResult.cc
6>AddGtmRecoveryPlanRequest.cc
6>AddGtmRecoveryPlanResult.cc
6>BindInstanceDomainsRequest.cc
6>正在生成代码...
6>正在编译...
6>BindInstanceDomainsResult.cc
6>ChangeDomainGroupRequest.cc
6>ChangeDomainGroupResult.cc
6>ChangeDomainOfDnsProductRequest.cc
6>ChangeDomainOfDnsProductResult.cc
6>DeleteCustomLinesRequest.cc
6>DeleteCustomLinesResult.cc
6>DeleteDomainRequest.cc
6>DeleteDomainResult.cc
6>DeleteDomainGroupRequest.cc
6>DeleteDomainGroupResult.cc
6>DeleteDomainRecordRequest.cc
6>DeleteDomainRecordResult.cc
6>DeleteGtmAccessStrategyRequest.cc
6>DeleteGtmAccessStrategyResult.cc
6>DeleteGtmAddressPoolRequest.cc
6>DeleteGtmAddressPoolResult.cc
6>DeleteGtmRecoveryPlanRequest.cc
6>DeleteGtmRecoveryPlanResult.cc
6>DeleteSubDomainRecordsRequest.cc
6>正在生成代码...
6>正在编译...
6>DeleteSubDomainRecordsResult.cc
6>DescribeBatchResultCountRequest.cc
6>DescribeBatchResultCountResult.cc
6>DescribeBatchResultDetailRequest.cc
6>DescribeBatchResultDetailResult.cc
6>DescribeCustomLineRequest.cc
6>DescribeCustomLineResult.cc
6>DescribeCustomLinesRequest.cc
6>DescribeCustomLinesResult.cc
6>DescribeDNSSLBSubDomainsRequest.cc
6>DescribeDNSSLBSubDomainsResult.cc
6>DescribeDnsProductInstanceRequest.cc
6>DescribeDnsProductInstanceResult.cc
6>DescribeDnsProductInstancesRequest.cc
6>DescribeDnsProductInstancesResult.cc
6>DescribeDomainGroupsRequest.cc
6>DescribeDomainGroupsResult.cc
6>DescribeDomainInfoRequest.cc
6>DescribeDomainInfoResult.cc
6>DescribeDomainLogsRequest.cc
6>正在生成代码...
6>正在编译...
6>DescribeDomainLogsResult.cc
6>DescribeDomainNsRequest.cc
6>DescribeDomainNsResult.cc
6>DescribeDomainRecordInfoRequest.cc
6>DescribeDomainRecordInfoResult.cc
6>DescribeDomainRecordsRequest.cc
6>DescribeDomainRecordsResult.cc
6>DescribeDomainStatisticsRequest.cc
6>DescribeDomainStatisticsResult.cc
6>DescribeDomainStatisticsSummaryRequest.cc
6>DescribeDomainStatisticsSummaryResult.cc
6>DescribeDomainsRequest.cc
6>DescribeDomainsResult.cc
6>DescribeGtmAccessStrategiesRequest.cc
6>DescribeGtmAccessStrategiesResult.cc
6>DescribeGtmAccessStrategyRequest.cc
6>DescribeGtmAccessStrategyResult.cc
6>DescribeGtmAccessStrategyAvailableConfigRequest.cc
6>DescribeGtmAccessStrategyAvailableConfigResult.cc
6>DescribeGtmAvailableAlertGroupRequest.cc
6>正在生成代码...
6>正在编译...
6>DescribeGtmAvailableAlertGroupResult.cc
6>DescribeGtmInstanceRequest.cc
6>DescribeGtmInstanceResult.cc
6>DescribeGtmInstanceAddressPoolRequest.cc
6>DescribeGtmInstanceAddressPoolResult.cc
6>DescribeGtmInstanceAddressPoolsRequest.cc
6>DescribeGtmInstanceAddressPoolsResult.cc
6>DescribeGtmInstanceStatusRequest.cc
6>DescribeGtmInstanceStatusResult.cc
6>DescribeGtmInstanceSystemCnameRequest.cc
6>DescribeGtmInstanceSystemCnameResult.cc
6>DescribeGtmInstancesRequest.cc
6>DescribeGtmInstancesResult.cc
6>DescribeGtmLogsRequest.cc
6>DescribeGtmLogsResult.cc
6>DescribeGtmMonitorAvailableConfigRequest.cc
6>DescribeGtmMonitorAvailableConfigResult.cc
6>DescribeGtmMonitorConfigRequest.cc
6>DescribeGtmMonitorConfigResult.cc
6>DescribeGtmRecoveryPlanRequest.cc
6>正在生成代码...
6>正在编译...
6>DescribeGtmRecoveryPlanResult.cc
6>DescribeGtmRecoveryPlanAvailableConfigRequest.cc
6>DescribeGtmRecoveryPlanAvailableConfigResult.cc
6>DescribeGtmRecoveryPlansRequest.cc
6>DescribeGtmRecoveryPlansResult.cc
6>DescribeRecordLogsRequest.cc
6>DescribeRecordLogsResult.cc
6>DescribeRecordStatisticsRequest.cc
6>DescribeRecordStatisticsResult.cc
6>DescribeRecordStatisticsSummaryRequest.cc
6>DescribeRecordStatisticsSummaryResult.cc
6>DescribeSubDomainRecordsRequest.cc
6>DescribeSubDomainRecordsResult.cc
6>DescribeSupportLinesRequest.cc
6>DescribeSupportLinesResult.cc
6>DescribeTransferDomainsRequest.cc
6>DescribeTransferDomainsResult.cc
6>ExecuteGtmRecoveryPlanRequest.cc
6>ExecuteGtmRecoveryPlanResult.cc
6>GetMainDomainNameRequest.cc
6>正在生成代码...
6>正在编译...
6>GetMainDomainNameResult.cc
6>GetTxtRecordForVerifyRequest.cc
6>GetTxtRecordForVerifyResult.cc
6>ModifyHichinaDomainDNSRequest.cc
6>ModifyHichinaDomainDNSResult.cc
6>OperateBatchDomainRequest.cc
6>OperateBatchDomainResult.cc
6>PreviewGtmRecoveryPlanRequest.cc
6>PreviewGtmRecoveryPlanResult.cc
6>RetrieveDomainRequest.cc
6>RetrieveDomainResult.cc
6>RollbackGtmRecoveryPlanRequest.cc
6>RollbackGtmRecoveryPlanResult.cc
6>SetDNSSLBStatusRequest.cc
6>SetDNSSLBStatusResult.cc
6>SetDomainRecordStatusRequest.cc
6>SetDomainRecordStatusResult.cc
6>SetGtmAccessModeRequest.cc
6>SetGtmAccessModeResult.cc
6>SetGtmMonitorStatusRequest.cc
6>正在生成代码...
6>正在编译...
6>SetGtmMonitorStatusResult.cc
6>TransferDomainRequest.cc
6>TransferDomainResult.cc
6>UnbindInstanceDomainsRequest.cc
6>UnbindInstanceDomainsResult.cc
6>UpdateCustomLineRequest.cc
6>UpdateCustomLineResult.cc
6>UpdateDNSSLBWeightRequest.cc
6>UpdateDNSSLBWeightResult.cc
6>UpdateDomainGroupRequest.cc
6>UpdateDomainGroupResult.cc
6>UpdateDomainRecordRequest.cc
6>UpdateDomainRecordResult.cc
6>UpdateDomainRecordRemarkRequest.cc
6>UpdateDomainRecordRemarkResult.cc
6>UpdateDomainRemarkRequest.cc
6>UpdateDomainRemarkResult.cc
6>UpdateGtmAccessStrategyRequest.cc
6>UpdateGtmAccessStrategyResult.cc
6>UpdateGtmAddressPoolRequest.cc
6>正在生成代码...
6>正在编译...
6>UpdateGtmAddressPoolResult.cc
6>UpdateGtmInstanceGlobalConfigRequest.cc
6>UpdateGtmInstanceGlobalConfigResult.cc
6>UpdateGtmMonitorRequest.cc
6>UpdateGtmMonitorResult.cc
6>UpdateGtmRecoveryPlanRequest.cc
6>UpdateGtmRecoveryPlanResult.cc
6>正在生成代码...
6>x64\Release\AlidnsClient.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突
6>已完成生成项目“alidns.vcxproj”的操作 - 失败。
7>------ 已启动全部重新生成: 项目: ALL_BUILD, 配置: Release x64 ------
7>Building Custom Rule F:/aliyun-openapi-cpp-sdk/CMakeLists.txt
8>------ 已启动全部重新生成: 项目: INSTALL, 配置: Release x64 ------
8>-- Install configuration: "Release"
8>-- Up-to-date: C:/Program Files (x86)/alibabacloud-sdk/include/alibabacloud/core/AlibabaCloud.h
8>CMake Error at core/cmake_install.cmake:36 (file):
8>  file INSTALL cannot set permissions on "C:/Program Files
8>  (x86)/alibabacloud-sdk/include/alibabacloud/core/AlibabaCloud.h":
8>  Permission denied.
8>Call Stack (most recent call first):
8>  cmake_install.cmake:38 (include)
8>
8>
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: 命令“setlocal
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: "D:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
8>D:\Program Files\Visual Stdio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd”已退出，代码为 1。
8>已完成生成项目“INSTALL.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 5 个，失败 3 个，跳过 0 个 ==========

**Comment by UnknownObject000** [comment]
@sdk-team

**Comment by AxiosCros** [comment]
在 CMake 的时候，要选择 64 位的。
而不是在生成好解决方案后，在 vs 里操作。

如下图操作:
![image](https://user-images.githubusercontent.com/13862149/71863801-f9f90e80-3138-11ea-82f2-c9298a5b6077.png)

**Comment by AxiosCros** [comment]
@UnknownObject000 
注意 CMake 和 vs 都需要管理员启动

**Comment by UnknownObject000** [comment]
编译已成功，感谢 @AxiosCros 。我将关闭这个issues
