### ISSUE TITLE
Quick Example in README.md cannot run successfully

### ISSUE THREAD

**Issue by philohack** [aliyun/aliyun-openapi-cpp-sdk#92]
Product and API: DescribeInstances API of ECS

Platform: Linux NGC 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

How to Reproduce: 
(1)Download release aliyun-openapi-cpp-sdk-1.36.237.zip, build following the steps in README.md.
(2)Copy the quick example in README.md to file ecs_test.cc, change the region_id, access_key_id and access_key_secret, build without errors.
(3)Run using ./ecstest, error occurs, it says as below:
terminate called after throwing an instance of 'Json::LogicError'
  what():  in Json::Value::resolveReference(key, end): requires objectValue
Aborted

**Comment by AxiosCros** [comment]
I didn't reproduce the problem, please show some stack trace information.

**Comment by AxiosCros** [comment]
compilation script with follows :

```bash
# build
g++ -o ecs_test.out ecs_test.cc --std=c++11 -lalibabacloud-sdk-core -l alibabacloud-sdk-ecs

# run
./ecs_test.out
```

ecs_test.cc code source is copied from the quick example. then , I got success response.
